temporalPath='./landing/temporal/'
persistentPath='./landing/persistent/'
dataBasesDir='C:/Users/odyky/Desktop/Databases/' # CHANGE THIS
formattedDataBasesDir = dataBasesDir + 'formatted/'
trustedDataBasesDir = dataBasesDir + 'trusted/'
profilingDir = 'C:/Users/odyky/Desktop/profiling/' # CHANGE THIS
profilingPlotsDir = profilingDir + 'plots/'
outliersDir = 'C:/Users/odyky/Desktop/outliers/' # CHANGE THIS
outliersPlotsDir = outliersDir + 'plots/'
exploitationDatabasesDir = dataBasesDir + 'exploitation/'